database:
  mongo:
    url: sensitive
middlewares:
  cors:
    activate: true
    origin: ''
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTION
port: 3300    
routing:
  base: "/api"
jsonLimit: 2mb
